### ISSUE TITLE
Strange decompile result when use null propagator on generic type

### ISSUE THREAD

**Issue by OpportunityLiu** [icsharpcode/ILSpy#1050]
Source:
``` C#
public struct Test<T1, T2>
    where T1 : class
{
    public T1 Item1;
    public T2 Item2;

    public int? Test1()
    {
        return Item1?.GetHashCode();
    }

    public int? Test2()
    {
        return Item2?.GetHashCode();
    }
}
```

Decompile result:
``` C#
public struct Test<T1, T2> where T1 : class
{
	public T1 Item1;

	public T2 Item2;

	public int? Test1()
	{
		object obj = this.Item1;
		return (obj != null) ? new int?(obj.GetHashCode()) : null;
	}

	public unsafe int? Test2()
	{
		? val = ref this.Item2;
		T2 val2 = default(T2);
		object result;
		if (val2 == null)
		{
			val2 = *(T2*)val;
			val = ref val2;
			if (val2 == null)
			{
				result = null;
				goto IL_0043;
			}
		}
		result = new int?(((object)val).GetHashCode());
		goto IL_0043;
		IL_0043:
		return (int?)result;
	}
}
```

**Comment by dgrunwald** [comment]
I fixed the handling of generics and handling of compiler-generated ref-locals.

If you add a `class` constraint (as with `Test1`), or if you first copy the value into a local variable (this avoids the compiler-generated ref-local):
```
			public int? Test2b()
			{
				var it = Item2;
				return it?.GetHashCode();
			}
```
then the generated code pattern changes and ILSpy (with my fixes) can reconstruct the `?.` operator.

But the combination of these two aspects (unconstrained generic + non-local target) causes this weird pattern in the generated code (what's the point of the ref-assignment???). We'd need to add a whole new `?.` recognizer just for this case.

The new output for your example is now:
```
public struct Test<T1, T2> where T1 : class
{
	public T1 Item1;
	public T2 Item2;

	public int? Test1()
	{
		return this.Item1?.GetHashCode();
	}

	public int? Test2()
	{
		ref T2 val = ref this.Item2;
		T2 val2 = default(T2);
		int? result;
		if (val2 == null)
		{
			val2 = val;
			val = ref val2; // ref local reassignment, will be valid code in a future C# version
			if (val2 == null)
			{
				result = null;
				goto IL_0043;
			}
		}
		result = val.GetHashCode();
		goto IL_0043;
		IL_0043:
		return result;
	}
}
```

**Comment by siegfriedpammer** [comment]
Triage: Even with our recent enhancements in the area of ref-typed variables, this issue persists.

**Comment by tamlin-mike** [comment]
Alternative repro (to keep github issue count down; core problem seems to be the same):

- Open from GAC
- mscorlib 4.0.0.0
- ValueTuple<T1>

Decompile its ToString.
